In [2]:
import pprint
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix




In [7]:
matchup_data = pd.read_csv("data/matchup_data.csv")

x_data = matchup_data[['diff_assists', 'diff_denies', 'diff_first_blood', 'diff_gpm', 'diff_healing', 'diff_hero_damage', 'diff_kills', 'diff_last_hits', 'diff_match_duration', 'diff_total_levels', 'diff_tower_damage', 'diff_xpm']]
y_data = matchup_data.radiant_winner

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size = 0.33, random_state = 12)
model = LogisticRegression()
model.fit(x_train, y_train)
prediction = dict()
prediction['Logistic'] = model.predict(x_test)

print('Log: ',accuracy_score(y_test, prediction['Logistic']))
print(model.coef_)

conf_mat_logist = confusion_matrix(y_test, prediction['Logistic'])
print('Logist \r', conf_mat_logist)

Log:  0.6333333333333333
[[-1.80441987e-02 -2.43455877e-02 -7.50670871e-03  1.09857352e-04
  -8.74557033e-05 -2.51723574e-05  1.27777731e-02 -6.45993469e-03
  -3.08799363e-03  2.89245533e-01  3.86533828e-04 -3.92267432e-03]]
 [[13  8]
 [14 25]]


In [11]:
prob= model.predict_proba(x_test)

model.score(x_train , y_train)

0.7058823529411765

In [12]:
prob

array([[0.14527854, 0.85472146],
       [0.85852076, 0.14147924],
       [0.22872981, 0.77127019],
       [0.50694686, 0.49305314],
       [0.16593535, 0.83406465],
       [0.50694686, 0.49305314],
       [0.50750189, 0.49249811],
       [0.06998212, 0.93001788],
       [0.50694686, 0.49305314],
       [0.36984115, 0.63015885],
       [0.60566071, 0.39433929],
       [0.56943971, 0.43056029],
       [0.34804717, 0.65195283],
       [0.23001715, 0.76998285],
       [0.56564491, 0.43435509],
       [0.36876609, 0.63123391],
       [0.15905554, 0.84094446],
       [0.9162923 , 0.0837077 ],
       [0.60742667, 0.39257333],
       [0.34654666, 0.65345334],
       [0.50694686, 0.49305314],
       [0.40339974, 0.59660026],
       [0.36417406, 0.63582594],
       [0.16562824, 0.83437176],
       [0.46575   , 0.53425   ],
       [0.38534516, 0.61465484],
       [0.44423618, 0.55576382],
       [0.36798707, 0.63201293],
       [0.50694686, 0.49305314],
       [0.52616358, 0.47383642],
       [0.

In [13]:
model.coef_

array([[-1.80441987e-02, -2.43455877e-02, -7.50670871e-03,
         1.09857352e-04, -8.74557033e-05, -2.51723574e-05,
         1.27777731e-02, -6.45993469e-03, -3.08799363e-03,
         2.89245533e-01,  3.86533828e-04, -3.92267432e-03]])

In [19]:
from sklearn import datasets, linear_model
from sklearn.model_selection import cross_validate
from sklearn.metrics.scorer import make_scorer
from sklearn.metrics import confusion_matrix
from sklearn.svm import LinearSVC

In [20]:
lasso = linear_model.Lasso()

In [21]:
cv_results = cross_validate(lasso, x_test, y_test, return_train_score=False)

In [22]:
sorted(cv_results.keys()) 

['fit_time', 'score_time', 'test_score']

In [24]:
cv_results['test_score'] 

array([0.29737329, 0.18194416, 0.09695652])