In [1]:
import pprint
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.metrics import log_loss, make_scorer




In [22]:
matchup_data = pd.read_csv("data/matchup_data.csv")

x_data = matchup_data[['diff_assists', 'diff_denies', 'diff_first_blood', 'diff_gpm', 'diff_healing', 'diff_hero_damage', 'diff_kills', 'diff_last_hits', 'diff_match_duration', 'diff_total_levels', 'diff_tower_damage', 'diff_xpm']]
y_data = matchup_data.radiant_winner

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size = 0.33, random_state = 14)
model = LogisticRegression()
model.fit(x_train, y_train)
prediction = dict()
prediction['Logistic'] = model.predict(x_test)

print('Log: ',accuracy_score(y_test, prediction['Logistic']))
print(model.coef_)

conf_mat_logist = confusion_matrix(y_test, prediction['Logistic'])
print('Logist \r', conf_mat_logist)

Log:  0.6587301587301587
[[ 4.76132162e-03  2.77220083e-03  8.83801155e-04  2.58388686e-03
   1.64851571e-05  2.46983104e-05  2.98051384e-02  4.78159307e-03
  -3.06025344e-03 -7.61485913e-02  1.80969827e-04  2.21736832e-05]]
 [[32 26]
 [17 51]]


In [23]:
prob= model.predict_proba(x_test)

print(f"log loss = {log_loss(y_test, model.predict_proba(x_test)[:, 1])}")
print(f"accuracy = {model.score(x_test, y_test)}")


log loss = 0.6118882357317612
accuracy = 0.6587301587301587


In [24]:
prob

array([[0.52550539, 0.47449461],
       [0.41869346, 0.58130654],
       [0.18833044, 0.81166956],
       [0.47428038, 0.52571962],
       [0.17275238, 0.82724762],
       [0.10813585, 0.89186415],
       [0.53636447, 0.46363553],
       [0.5221562 , 0.4778438 ],
       [0.71154735, 0.28845265],
       [0.25272432, 0.74727568],
       [0.31839122, 0.68160878],
       [0.69796306, 0.30203694],
       [0.55471934, 0.44528066],
       [0.77372503, 0.22627497],
       [0.2837976 , 0.7162024 ],
       [0.41869346, 0.58130654],
       [0.12980716, 0.87019284],
       [0.55611373, 0.44388627],
       [0.39626655, 0.60373345],
       [0.35544269, 0.64455731],
       [0.12724429, 0.87275571],
       [0.54542099, 0.45457901],
       [0.5825925 , 0.4174075 ],
       [0.15608347, 0.84391653],
       [0.84818553, 0.15181447],
       [0.4623349 , 0.5376651 ],
       [0.39045355, 0.60954645],
       [0.65094836, 0.34905164],
       [0.21648773, 0.78351227],
       [0.07955893, 0.92044107],
       [0.

In [25]:
model.coef_

array([[ 4.76132162e-03,  2.77220083e-03,  8.83801155e-04,
         2.58388686e-03,  1.64851571e-05,  2.46983104e-05,
         2.98051384e-02,  4.78159307e-03, -3.06025344e-03,
        -7.61485913e-02,  1.80969827e-04,  2.21736832e-05]])

In [26]:

from sklearn.model_selection import cross_validate
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error


In [27]:
cv_results = cross_validate(model, x_data, y_data,cv=5,scoring='accuracy')

In [28]:
sorted(cv_results.keys()) 

['fit_time', 'score_time', 'test_score', 'train_score']

In [29]:
cv_results['test_score'] 

array([0.61038961, 0.64473684, 0.63157895, 0.64473684, 0.65789474])

In [30]:
cv_results['train_score'] 

/home/jonathan/anaconda3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)


array([0.65789474, 0.70163934, 0.70491803, 0.69180328, 0.69180328])

In [11]:
cv_scores = cross_val_score(model, x_test, y_test,cv=5,scoring='accuracy')

In [12]:
cv_scores

array([0.76923077, 0.53846154, 0.5       , 0.58333333, 0.625     ])